
class RC:
    OK = AMGX_RC_OK
    BAD_PARAMETERS = AMGX_RC_BAD_PARAMETERS
    UNKNOWN = AMGX_RC_UNKNOWN
    NOT_SUPPORTED_TARGET = AMGX_RC_NOT_SUPPORTED_TARGET 
    NOT_SUPPORTED_BLOCKSIZE = AMGX_RC_NOT_SUPPORTED_BLOCKSIZE 
    CUDA_FAILURE = AMGX_RC_CUDA_FAILURE 
    THRUST_FAILURE = AMGX_RC_THRUST_FAILURE
    NO_MEMORY = AMGX_RC_NO_MEMORY
    IO_ERROR = AMGX_RC_IO_ERROR
    BAD_MODE = AMGX_RC_BAD_MODE
    CORE = AMGX_RC_CORE
    PLUGIN = AMGX_RC_PLUGIN
    BAD_CONFIGURATION = AMGX_RC_BAD_CONFIGURATION
    NOT_IMPLEMENTED = AMGX_RC_NOT_IMPLEMENTED
    LICENSE_NOT_FOUND = AMGX_RC_LICENSE_NOT_FOUND
    INTERNAL = AMGX_RC_INTERNAL
